apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template: # Pod definition goes below
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-pod
        image: subratohld/user-service:c7373fb
        imagePullPolicy: Never # Fetch image from local registry (Always/Never/IfNotPresent)
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: user-svc-cm
--- 
# Service definition goes below
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 # 30000 - 32767 